module CentralEventLogger
  module EventTypes
    CHURN: string
    CONVERSION: string
    ENGAGEMENT: string
    FEEDBACK: string
    MARKETING: string
    PERFORMANCE: string
    SETTINGS_CHANGE: string
    SUPPORT: string
    USER_ACQUISITION: string
    STATISTICS: string
  end
end
