test:
  adapter: postgresql
  database: centralized_logging_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

